// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::character_health_type::CharacterHealth;
use super::character_type_type::CharacterType;
use super::db_vec_3_type::DbVec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterTable {
    pub npc_id: i64,
    pub name: String,
    pub position: DbVec3,
    pub health: CharacterHealth,
    pub speed: f32,
    pub is_moving: bool,
    pub is_targettable: bool,
    pub character_type: CharacterType,
}

impl __sdk::InModule for CharacterTable {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterTable`.
///
/// Provides typed access to columns for query building.
pub struct CharacterTableCols {
    pub npc_id: __sdk::__query_builder::Col<CharacterTable, i64>,
    pub name: __sdk::__query_builder::Col<CharacterTable, String>,
    pub position: __sdk::__query_builder::Col<CharacterTable, DbVec3>,
    pub health: __sdk::__query_builder::Col<CharacterTable, CharacterHealth>,
    pub speed: __sdk::__query_builder::Col<CharacterTable, f32>,
    pub is_moving: __sdk::__query_builder::Col<CharacterTable, bool>,
    pub is_targettable: __sdk::__query_builder::Col<CharacterTable, bool>,
    pub character_type: __sdk::__query_builder::Col<CharacterTable, CharacterType>,
}

impl __sdk::__query_builder::HasCols for CharacterTable {
    type Cols = CharacterTableCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterTableCols {
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            speed: __sdk::__query_builder::Col::new(table_name, "speed"),
            is_moving: __sdk::__query_builder::Col::new(table_name, "is_moving"),
            is_targettable: __sdk::__query_builder::Col::new(table_name, "is_targettable"),
            character_type: __sdk::__query_builder::Col::new(table_name, "character_type"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterTable`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterTableIxCols {
    pub npc_id: __sdk::__query_builder::IxCol<CharacterTable, i64>,
}

impl __sdk::__query_builder::HasIxCols for CharacterTable {
    type IxCols = CharacterTableIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterTableIxCols {
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterTable {}
