// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_health_type::CharacterHealth;
use super::character_table_type::CharacterTable;
use super::character_type_type::CharacterType;
use super::db_vec_3_type::DbVec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character`.
///
/// Obtain a handle from the [`CharacterTableAccess::character`] method on [`super::RemoteTables`],
/// like `ctx.db.character()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character().on_insert(...)`.
pub struct CharacterTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterTable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterTableHandle`], which mediates access to the table `character`.
    fn character(&self) -> CharacterTableHandle<'_>;
}

impl CharacterTableAccess for super::RemoteTables {
    fn character(&self) -> CharacterTableHandle<'_> {
        CharacterTableHandle {
            imp: self.imp.get_table::<CharacterTable>("character"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterInsertCallbackId(__sdk::CallbackId);
pub struct CharacterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterTableHandle<'ctx> {
    type Row = CharacterTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterTable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterInsertCallbackId {
        CharacterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterDeleteCallbackId {
        CharacterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CharacterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterTableHandle<'ctx> {
    type UpdateCallbackId = CharacterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterUpdateCallbackId {
        CharacterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `npc_id` unique index on the table `character`,
/// which allows point queries on the field of the same name
/// via the [`CharacterNpcIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character().npc_id().find(...)`.
pub struct CharacterNpcIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterTable, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterTableHandle<'ctx> {
    /// Get a handle on the `npc_id` unique index on the table `character`.
    pub fn npc_id(&self) -> CharacterNpcIdUnique<'ctx> {
        CharacterNpcIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("npc_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterNpcIdUnique<'ctx> {
    /// Find the subscribed row whose `npc_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<CharacterTable> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterTable>("character");
    _table.add_unique_constraint::<i64>("npc_id", |row| &row.npc_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterTable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterTable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterTable`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait characterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterTable`.
    fn character(&self) -> __sdk::__query_builder::Table<CharacterTable>;
}

impl characterQueryTableAccess for __sdk::QueryTableAccessor {
    fn character(&self) -> __sdk::__query_builder::Table<CharacterTable> {
        __sdk::__query_builder::Table::new("character")
    }
}
